---
title: AWS 호스팅 EC2 와 Lightsail의 차이
subtitle: AWS 호스팅 EC2 와 Lightsail의 차이
description:
    AWS 호스팅 EC2 와 Lightsail의 차이
categories:
  - DevOps
author: gabriel yang
date: "11/26/2023"
image: "https://picsum.photos/id/222/200/150"
# image-alt: "deep learning glossary"
page-layout: article
# draft: true
---

# 블로그용 AWS, EC2와 Lightsail의 차이

AWS는 어플리케이션이나 블로그의 호스팅을 원하는 사용자를 위해서 `EC2(Amazon Elastic Compute Cloud)`와 `Lightsail`을 제공합니다. 두 개의 서비스가 어떤 차이가 있는 지 정리합니다.

EC2에는 여러 서비스가 혼합되어 있으며 단일 아키텍처를 생성하는 데 사용되는 고유한 개별 기능을 가지고 있으며 소규모 내지 복잡한 아키텍처에 적합합니다. 반면 Lightsail은 AWS에서 제공하는 통합 서비스 제품으로 Lightsail은 소규모 내지 중간 규모의 워크로드에 더 적합합니다. 주요 차이점을 표로 정리해서 비교합니다.

|             | Lightsail             | EC2                       |
|------------|------------------------|---------------------------|
| 사용        | 사용자 지정 코드 및 일반 CMS를 포함한 간단한 웹 애플리케이션 및 웹 사이트에 사용됩니다.                                                            | HPC, 빅 데이터 및 분석 워크로드와 같은 소규모 내지 엔터프라이즈 애플리케이션에 사용됩니다.                                                              |
| 관리 지원   | Lightsail에서는 시스템 관리자와 시스템 아키텍트의 수고를 덜 수 있습니다.                                                                           | 환경 유형에 따라 관리에 필요한 노력이 달라집니다. EC2의 대부분의 서비스는 구성 요소에 대한 철저한 이해가 필요합니다.                                    |
| 확장성      | Lightsail에서 자동 인스턴스 확장성은 지원되지 않습니다.시작 후에는 인스턴스를 수정할 수 없습니다. 플랜을 변경하려면 새 인스턴스를 시작해야 합니다. | Amazon EC2 Auto Scaling 그룹을 사용하여 인스턴스를 자동으로 크기 조정할 수 있습니다.EC2 인스턴스는 새로운 유형 또는 새로운 가상화로 수정할 수 있습니다. |
| 탄력적 볼륨 | 지원되지 않음                                                                                                                                      | 지원됨                                                                                                                                                  |
| 로드 밸런싱 | Lightsail 인스턴스에서는 Lightsail 로드 밸런서를 사용할 수 있습니다.                                                                               | 여러 유형의 로드 밸런서를 사용할 수 있습니다.                                                                                                           |

표에서 알 수 있듯이 EC는 블로그나 간단한 어플리케이션 운영을 위해서라면 `Lightsail`이 적합한 호스팅 서비스로 보입니다. 하지만 장기적으로 다양한 서비스와 연동될 수 있는 확장성에 대한 고려가 필요하다면 `EC2`를 고려하면 좋을 것 같습니다. 

주의해야 할 기능은 `탄력적 볼륨`인 것 같습니다. 이 기능은 필요에 따라서 데이터 용량이너 성능 요구사항의 변경이 필요할 때 유용한 기능입니다. 고려하는 서비스가 특정 기간에 서비스 요청이 늘어날 것을 예상한다면 선택에 중요한 요소가 될 수 있습니다.

# References

1.  https://repost.aws/ko/knowledge-center/lightsail-differences-from-ec2