---
title: Subway
author: Gabriel Yang
date: 07/23/2023
page-layout: article
published: true
---

# Transportation

In Korea's big cities, it is convenient to use the subway to get around.
Let's learn how to find nearest subway.

::: {.callout-note icon=false}
## Transportation - Subway   
Where is the nearest subway station? - 가까운 지하철 역이 어디인가요?
:::

You can use `어디인가요?` when looking for a location. The object to find the location is a subway station, which means `지하철 역` in Korean.
We use `가까운` to find the nearest subway station. Use '가까운' in front of the word `지하철역` to give additional information about the 'subway station'. Now it has the meaning of a subway station close to your location.
Check the pronunciation in the table below


| English                             | Korean                       | Pronunciation    |
|-------------------------------------| -----------------------------| -----------------|
|Where is the nearest subway station? | 가까운 지하철 역이 어디인가요? | <a href="https://www.google.com/search?q=%EC%A7%80%ED%95%98%EC%B2%A0+%EC%82%AC%EC%A0%84&sca_esv=560391173&ei=BIzqZJfuHvXPseMPhYKNgAI&ved=0ahUKEwiXgP-3vvuAAxX1Z2wGHQVBAyAQ4dUDCBA&uact=5&oq=%EC%A7%80%ED%95%98%EC%B2%A0+%EC%82%AC%EC%A0%84&gs_lp=Egxnd3Mtd2l6LXNlcnAiEOyngO2VmOyyoCDsgqzsoIRIpxxQ2QVYpBtwB3gBkAEAmAHSAqABygyqAQc5LjIuMS4xuAEDyAEA-AEBqAIAwgIKEAAYRxjWBBiwA8ICBxAAGIoFGEPCAgsQLhiABBixAxiDAcICDRAuGIoFGMcBGNEDGEPCAgUQABiABMICCBAAGIAEGLEDwgILEAAYgAQYsQMYgwHCAgQQLhgDwgIFEC4YgATCAg4QLhiABBixAxjHARjRA8ICERAuGIAEGLEDGIMBGMcBGNEDwgIEEAAYA8ICCBAuGIAEGLED4gMEGAAgQYgGAZAGCg&sclient=gws-wiz-serp" target='_blank'>Google Translation</a>|



## Words
Check the words you have learned.

| English                             | Korean                       | Pronunciation    |
|-------------------------------------| -----------------------------| -----------------|
| Subway  | 지하철 | <a href="https://www.google.com/search?q=%EC%A7%80%ED%95%98%EC%B2%A0+%EC%82%AC%EC%A0%84&sca_esv=560391173&ei=BIzqZJfuHvXPseMPhYKNgAI&ved=0ahUKEwiXgP-3vvuAAxX1Z2wGHQVBAyAQ4dUDCBA&uact=5&oq=%EC%A7%80%ED%95%98%EC%B2%A0+%EC%82%AC%EC%A0%84&gs_lp=Egxnd3Mtd2l6LXNlcnAiEOyngO2VmOyyoCDsgqzsoIRIpxxQ2QVYpBtwB3gBkAEAmAHSAqABygyqAQc5LjIuMS4xuAEDyAEA-AEBqAIAwgIKEAAYRxjWBBiwA8ICBxAAGIoFGEPCAgsQLhiABBixAxiDAcICDRAuGIoFGMcBGNEDGEPCAgUQABiABMICCBAAGIAEGLEDwgILEAAYgAQYsQMYgwHCAgQQLhgDwgIFEC4YgATCAg4QLhiABBixAxjHARjRA8ICERAuGIAEGLEDGIMBGMcBGNEDwgIEEAAYA8ICCBAuGIAEGLED4gMEGAAgQYgGAZAGCg&sclient=gws-wiz-serp)" target='_blank'>Google Translation</a> |
