---
title: SQL 정렬 명령 order by
subtitle: SQL 정렬 명령 order by
description:
  SQL 정렬 명령 order by
categories:
  - Database
# All, Data Visualization, Database, DevOps, Pandas, Quarto, Web, HuggingFace
author: gabriel yang
date: "1/5/2024"
image: "https://picsum.photos/id/115/200/150"
# image-alt: "deep learning glossary"
page-layout: article
execute:
  echo: false
---

# SQL 레코드 정렬하기

이 글에서는 SQL의 ORDER BY 구문을 사용하는 실제 예시를 살펴보겠습니다. 먼저, 간단한 가상의 데이터베이스 정보를 설정하고, 이를 기반으로 ORDER BY 구문을 사용하는 다양한 쿼리와 그 결과를 보여드리겠습니다. 이를 통해, ORDER BY 구문의 사용방법을 정리합니다.

## 가상 데이터 구조

가상 데이터베이스 "StudentDB"를 사용하여 ORDER BY의 다중 정렬 기능을 살펴보겠습니다. "StudentDB"는 'Student' 테이블을 포함하며, 이름, 나이, 전공 등의 정보를 담고 있습니다.

| ID | Name   | Age | Major               |
|----|--------|-----|---------------------|
| 1  | Jim    | 20  | Computer Science    |
| 2  | Yuna   | 19  | Mathematics         |
| 3  | Hoseok | 20  | Physics             |
| 4  | Seong  | 21  | English Literature  |
| 5  | Min    | 20  | Biology             |

## 전공(Major)을 기준으로 오름차순 정렬

전공 컬럼을 오름차순으로 정렬하는 코드입니다. 전체 컬럼 정보를 `Student` 테이블에서 선택하고 `Major`컬럼을 오름차순으로 정렬합니다.

``` bash
SELECT * FROM Student
ORDER BY Major ASC;
```
| ID | Name   | Age | Major               |
|----|--------|-----|---------------------|
| 1  | Jim    | 20  | Computer Science    |
| 5  | Min    | 20  | Biology             |
| 4  | Seong  | 21  | English Literature  |
| 2  | Yuna   | 19  | Mathematics         |
| 3  | Hoseok | 20  | Physics             |


## 나이(Age)를 기준으로 내림차순 정렬

나이 컬럼을 내림차순으로 정렬하는 코드입니다. `Student` 테이블에서  `Name`, `Age`컬럼을 선택하고 `Age`컬럼을 내림차순으로 정렬합니다.

``` bash
SELECT Name, Age FROM Student
ORDER BY Age DESC;
```
| Name   | Age |
|--------|-----|
| Seong  | 21  |
| Jim    | 20  |
| Hoseok | 20  |
| Min    | 20  |
| Yuna   | 19  |

## 한개이상 정보를 사용하여 정렬하기

나이로 오름차순 정렬 후, 동일 나이일 경우 이름으로 내림차순 정렬하는 코드입니다. `Name`과 `Age` 컬럼을 선택했습니다. 나이가 `20`인 `Min`, `Jim`, `Hosok`은 내림차순으로 정렬됩니다.

``` bash
SELECT Name, Age FROM Student
ORDER BY Age ASC, Name DESC;
```
| Name   | Age |
|--------|-----|
| Yuna   | 19  |
| Min    | 20  |
| Jim    | 20  |
| Hoseok | 20  |
| Seong  | 21  |


