---
title: Pandas 데이터 전처리
subtitle: Pandas 데이터 타입 변경 전처리
description:
  Pandas 데이터 타입을 변경하는 방법, 데이터 전처리 방법을 정리합니다.
categories:
  - Pandas
author: gabriel yang
date: "09/10/2023"
image: "https://picsum.photos/id/110/200/150"
# image-alt: "deep learning glossary"
page-layout: article
---

# 테이터 전처리

데이터시각화 및 데이터분석을 위해 읽어온 원본 데이터의 데이터 타입이 올바른지 확인하지 않으면 분석과정에 사용하는 다양한 통계적 지표나 필터결과가 오류를 발생합니다. 데이터에 맞는 형식으로 변경되지 않은 데이터프레임을 사용할 때 발생하는 문제점을 확인하고 올바르게 데이터 형식으로 변경하는 과정을 정리합니다.



``` {python}
import pandas as pd
import datetime as dt

df = pd.DataFrame({"year": ['1900','1901','1910','2021', '2023'],
                   "n_sales" : ['10EA', '20EA', '40EA', '100EA', '210EA'],
                   "status" : ['good', 'bad', 'normal', 'bad', 'good']})
df
```

데이터 프레임은 `year`, `n_sales`, `status` 3개의 컬럼을 갖습니다. 각 컬럼이 어떤 데이터 타입인지 확인해볼까요? 데이터프레임의 정보를 보여주는 `info()`함수로 데이터 타입을 확인합니다.

``` {python}
df.info()
```

예상했던 데이터 형식과 다릅니다. `n_sales`는 숫자를 표현하고 있기 때문에 `int` 타입으로 표현되어야 할 것 같은데 `object`타입이네요. 데이터 프레임의 통계정보를 보여주는 `describe()`함수를 사용하면 차이를 알 수 있습니다.

``` {python}
df['n_sales'].describe()
```

위의 코드 실행결과에서 확인할 수 있는 것처럼 `n_sales`컬럼의 통계 정보는 `categorical` 통계정보가 출력됩니다. 숫자로 표현되지 않아서 예상했던 `평균`, `표준편차` 등의 정보는 알 수 없습니다.

## 데이터 타입 변경하기

데이터에 대한 적절한 전처리가 되지 않는 경우 잘못된 통계정보를 이용할 수 있기 때문에 적절한 전처리가 필요합니다. 위에서 만든 데이터프레임의 각 컬럼에 올바른 데이터타입을 적용해야 합니다.

``` {python}
# | echo: false
df
```

일반적으로 데이터 타입 변경은 데이터에 대한 이해가 필요합니다. `year`의 경우 날짜를 표현하고 있고 `n_sales`의 `EA`는 단위이기 때문에 꼭 필요한 정보가 아니라면 삭제 가능합니다. 이 두 가지 데이터 컬럼은 숫자를 표현하고 있으니 `int` 타입으로 변경합니다. 마지막 `status` 컬럼은 명백히 `categorical` 데이터입니다.

``` {python}
df['year'] = pd.to_datetime(df['year'])
df['n_sales'] = df['n_sales'].str.strip('EA').astype('int')
df['status'] = df['status'].astype('category')
```

위의 `to_datatime()`과 `astype()`함수를 이용해서 각 컬럼을 'datetime', 'int', 'categorical' 타입으로 변경했습니다. 단위를 제거하기 위해서 'strip()' 함수를 사용한 것을 참고하세요.

``` {python}
df.info()
```

수정된 데이터 프레임은 올바른 데이터 타입을 갖습니다. 이제 데이터프레임의 통계정보를 확인하겠습니다.

``` {python}
df['n_sales'].describe()
```

이제 예상한 것과 같이 `n_sales`에 대한 `평균`, `표준편차` 등의 통계정보를 확인할 수 있습니다.
