project:
  type: website

website:
  title: "Public KR Book"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - docs/book_blog/index.qmd
      #- books.qmd
      - about.qmd
  # google-analytics: "UA-XXXXXXXX"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true





