project:
  type: website

website:
  title: "Public KR Book"
  google-analytics:
    tracking-id: "G-FGHC552RY6"
  repo-url: https://github.com/gabrielwithappy/publickrbook/
  repo-subdir: website/
  repo-actions: [edit]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - docs/book_blog/index.qmd
      #- books.qmd
      - about.qmd

  sidebar:
    - id: get-started

    - id: hf-examples
      collapse-level: 1
      contents:
        - docs/bookshelf/hf-examples/index.qmd
        - section: "Task별 예제"
          contents:
            - section: "Video"
            - section: "Audio"
            - section: "NLP"
              contents:
                - docs/bookshelf/hf-examples/NLP/finance_news_sentiment.qmd

    - id: korean-study
      collapse-level: 1
      contents:
        - docs/bookshelf/korean-study/index.qmd
        - section: "Transportation"
          contents:
            - docs/bookshelf/korean-study/subway.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true





