project:
  type: website

metadata-files:
  - docs/bookshelf/korean/_sidebar.yml
  - docs/bookshelf/data_visualization/_sidebar.yml
  - docs/bookshelf/hf-examples/_sidebar.yml
  - docs/blog/posts/_sidebar.yml

website:
  title: "BookShelf"
  search: true
  site-url: https://gabrielwithappy.github.io/
  site-path: '/'
  description: "A online bookstore"
  google-analytics:
    tracking-id: "G-N916ZQ0D0N"
  page-footer:
    center: "gabrielwithhappy@gmail.com"
  repo-url: https://github.com/gabrielwithappy/gabrielwithappy.github.io
  repo-subdir: website/
  repo-actions: [edit]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - docs/blog/blog.qmd
      - docs/book_blog/book_blog.qmd
      - docs/slide_blog/slide_blog.qmd
      - about.qmd

execute:
  freeze: auto

format:
  html:
    theme: cosmo
    css: styles.css
    include-in-header:
      - text: <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1386106477710113" crossorigin="anonymous"></script>
    toc: true

adsense:
    client: "ca-pub-1386106477710113"   # data-ad-client
    # slot:   "f08c47fec0942fa0"                # data-ad-slot
