project:
  type: website

metadata-files:
  - bookshelf/korean/_sidebar.yml
  - blog/posts/_sidebar.yml
  - book_blog/posts/2024-06-29-plotly/_sidebar.yml
  - book_blog/posts/2023-09-03-data-visualization/_sidebar.yml

website:
  title: "BookShelf"
  search: true
  site-url: https://gabrielwithappy.github.io/
  site-path: '/'
  description: "A online bookstore"
  google-analytics:
    tracking-id: "G-N916ZQ0D0N"
  page-footer:
    center: "gabrielwithhappy@gmail.com"
  repo-url: https://github.com/gabrielwithappy/gabrielwithappy.github.io
  repo-subdir: website/
  repo-actions: [edit]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - blog/blog.qmd
      - book_blog/book_blog.qmd
      - dashboard_blog/dashboard_blog.qmd
      - about.qmd

# execute:
#   freeze: auto

format:
  html:
    theme: cosmo
    css: styles.css
    include-in-header:
      - text: <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1386106477710113" crossorigin="anonymous"></script>
    toc: true

adsense:
    client: "ca-pub-1386106477710113"   # data-ad-client
    # slot:   "f08c47fec0942fa0"                # data-ad-slot
