project:
  type: website

metadata-files:
  - docs/bookshelf/korean/_sidebar.yml
  - docs/bookshelf/data_visualization/_sidebar.yml
  - docs/bookshelf/hf-examples/_sidebar.yml

website:
  title: "BookShelf"
  search: true
  site-url: https://gabrielwithappy.github.io/
  site-path: '/'
  description: "A online bookstore"
  google-analytics:
    tracking-id: "G-FGHC552RY6"
  page-footer:
    center: "gabrielwithhappy@gmail.com"
  repo-url: https://github.com/gabrielwithappy/books/
  repo-subdir: website/
  repo-actions: [edit]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - docs/book_blog/index.qmd
      - docs/slide_blog/index.qmd
      - about.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

adsense:
    client: "ca-pub-1386106477710113"   # data-ad-client
    # slot:   "f08c47fec0942fa0"                # data-ad-slot
