project:
  type: website

website:
  title: "Public KR Book"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - docs/book_blog/index.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



