on:
  push:
    branches:
      - main

name: Render and Publish

# you need these permissions to publish to GitHub pages
# permissions:
#     contents: write
#     pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5

      - name : Install requirements
        run: |
          python3 -m pip install -U pip
          pip3 install -r requirements.txt

      - name: Set up Quarto and publish
        run: |
          sudo dpkg -i quarto-1.3.450-linux-amd64.deb
          cd website
          quarto publish --no-prompt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}