on:
  schedule:
    - cron: 0 0 * * *

name: Update Data

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup python
        uses: actions/setup-python@v5

      - name : Install requirements
        run: |
          python3 -m pip install -U pip
          pip3 install -r requirements.txt
          git config --global user.email "gabrielwithhappy@gmail.com"
          git config --global user.name "gabriel"

      - name: Update Data
        run: |
          cd utils
          ./update_graph_data.sh ${{secrets.ECOS_KEY}}
          git add ./utils
          git commit -m "update data"
          git push origin main
